# Generated by Django 4.0.3 on 2022-05-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vessels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='vessels',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.type'),
        ),
    ]
