# Generated by Django 4.0.3 on 2022-05-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_type_alter_vessels_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessels',
            name='photo',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
