# Generated by Django 4.0.3 on 2022-05-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_person_first_name_person_second_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('vessels', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='user.vessels')),
                ('b_r', models.CharField(max_length=50)),
                ('b_b', models.CharField(max_length=50)),
                ('b_c', models.CharField(max_length=50)),
                ('N', models.CharField(max_length=50)),
                ('Q', models.CharField(max_length=50)),
                ('V', models.CharField(max_length=50)),
                ('C', models.CharField(max_length=50)),
                ('K', models.CharField(max_length=50)),
                ('X', models.CharField(max_length=50)),
                ('E', models.CharField(max_length=50)),
            ],
        ),
    ]
