# Generated by Django 4.0.3 on 2022-05-18 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='vessels',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.vessels'),
        ),
    ]
