# Generated by Django 4.0.3 on 2022-05-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_fuel_vessels'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessels',
            name='latitude',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='vessels',
            name='longitude',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='vessels',
            name='name_in_en',
            field=models.CharField(default=models.CharField(max_length=100), max_length=300),
        ),
    ]
