# Generated by Django 4.0.3 on 2022-05-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_vessels_latitude_vessels_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessels',
            name='icon',
            field=models.ImageField(default='img/icons/красный.jpg', upload_to='img/icons'),
        ),
    ]
