# Generated by Django 4.0.3 on 2022-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_vessels_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessels',
            name='icon',
            field=models.ImageField(default='img/icons/краснsй.png', upload_to='img/icons'),
        ),
    ]
