# Generated by Django 4.0.3 on 2023-10-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_vessels_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessels',
            name='name_in_en',
            field=models.CharField(max_length=300),
        ),
    ]
